#!/usr/bin/env bash
# Variaveis partilhadas: preferir SLURM_MONITOR_* (open source); APUANA_MONITOR_* mantem compatibilidade.
# O script chamador deve definir SCRIPT_DIR antes de: source "${SCRIPT_DIR}/lib_env.sh"

: "${SCRIPT_DIR:?define SCRIPT_DIR before sourcing lib_env.sh}"

MONITOR_VENV="${SLURM_MONITOR_VENV:-${APUANA_MONITOR_VENV:-${SCRIPT_DIR}/.venv-monitor}}"
MONITOR_PORT="${SLURM_MONITOR_STREAMLIT_PORT:-${APUANA_MONITOR_STREAMLIT_PORT:-8501}}"
MONITOR_SESSION="${SLURM_MONITOR_SESSION:-${APUANA_MONITOR_SESSION:-SlurmMonitor}}"
MONITOR_LOG_OUT="${SLURM_MONITOR_LOG_OUT:-${APUANA_MONITOR_LOG_OUT:-${HOME}/slurm-dashboard.out}}"
MONITOR_LOG_ERR="${SLURM_MONITOR_LOG_ERR:-${APUANA_MONITOR_LOG_ERR:-}}"
MONITOR_SQUEUE_SEC="${SLURM_MONITOR_SQUEUE_SEC:-${APUANA_MONITOR_SQUEUE_SEC:-5}}"
MONITOR_GPU_SEC="${SLURM_MONITOR_GPU_SEC:-${APUANA_MONITOR_GPU_SEC:-10}}"
MONITOR_SACCT_SEC="${SLURM_MONITOR_SACCT_SEC:-${APUANA_MONITOR_SACCT_SEC:-30}}"
MONITOR_SACCT_LINES="${SLURM_MONITOR_SACCT_LINES:-${APUANA_MONITOR_SACCT_LINES:-18}}"
